name: CI

on:
  push:
    workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Create User Account
        run: |
          sudo sysadminctl -addUser runneradmin -password "Rabiu2004@" -home /Users/runneradmin -admin
        shell: bash

      - name: Enable SSH access
        run: sudo systemsetup -setremotelogin on
        shell: bash

      - name: Start SSH Service
        run: sudo launchctl load /System/Library/LaunchDaemons/ssh.plist
        shell: bash

      - name: Download ngrok
        run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip -O ngrok.zip
        shell: bash

      - name: Extract ngrok
        run: unzip ngrok.zip
        shell: bash

      - name: Authenticate ngrok
        run: ./ngrok authtoken 2Hd7yeF4INCKbg2aP9rGMLnDqBX_5K7WhATjW8eUxS6UoHSRa
        shell: bash

      - name: Create SSH Tunnel
        run: ./ngrok tcp 22
        shell: bash

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        shell: bash

      - name: Install essential tools
        run: |
          brew install wget curl
          # Add more essential tools as needed
        shell: bash
