name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CHROME_REMOTE_DESKTOP_CODE: "4/0AfJohXlr3vfdA2kIi4la78C_DylP8hikuYDJ3co-BxKKU2kUdxVn1fH31bONaeVF3o3PLA"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Create User Account
        run: |
          sudo sysadminctl -addUser runneradmin -password "Rabiu2004@" -home /Users/runneradmin -admin
        shell: bash

      - name: Enable SSH access
        run: sudo systemsetup -setremotelogin on
        shell: bash

      - name: Start SSH Service
        run: sudo launchctl load /System/Library/LaunchDaemons/ssh.plist
        shell: bash

      - name: Install required tools
        run: |
          brew install curl
        shell: bash

      # Download Chrome Remote Desktop
      - name: Download Chrome Remote Desktop
        run: |
          curl -O https://dl.google.com/chrome-remote-desktop/chromeremotedesktop.dmg
          hdiutil attach chromeremotedesktop.dmg
          ls "/Volumes"
          ls "$PWD"
          mounted_volume_path=$(ls -d "/Volumes/Chrome Remote Desktop Host "* | head -n 1)
          if [ -d "$mounted_volume_path" ]; then
            ls "$mounted_volume_path"
            sudo installer -package "$mounted_volume_path/Chrome Remote Desktop.pkg" -target /
          else
            echo "Error: Chrome Remote Desktop volume not found"
            exit 1
          fi
          hdiutil detach "$mounted_volume_path"
          rm chromeremotedesktop.dmg
        shell: bash

      # Start Chrome Remote Desktop using environment variables
      - name: Start Chrome Remote Desktop
        run: |
          DISPLAY= /opt/google/chrome-remote-desktop/start-host \
          --code="$CHROME_REMOTE_DESKTOP_CODE" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --name=$(hostname)
        shell: bash
