name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CHROME_REMOTE_DESKTOP_CODE: "4/0AfJohXlr3vfdA2kIi4la78C_DylP8hikuYDJ3co-BxKKU2kUdxVn1fH31bONaeVF3o3PLA"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ... (your existing steps)

      - name: Download Chrome Remote Desktop
        run: |
          curl -O https://dl.google.com/chrome-remote-desktop/chromeremotedesktop.dmg
          hdiutil mount chromeremotedesktop.dmg
          sudo installer -package "/Volumes/Chrome Remote Desktop/Chrome Remote Desktop.pkg" -target /
          hdiutil unmount "/Volumes/Chrome Remote Desktop"
          rm chromeremotedesktop.dmg
        shell: bash

      # Start Chrome Remote Desktop using environment variables
      - name: Start Chrome Remote Desktop
        run: |
          DISPLAY= /opt/google/chrome-remote-desktop/start-host \
          --code="$CHROME_REMOTE_DESKTOP_CODE" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --name=$(hostname)
        shell: bash
