name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Create User Account
        run: |
          sudo sysadminctl -addUser runneradmin -password "Rabiu2004@" -home /Users/runneradmin -admin
        shell: bash

      - name: Enable SSH access
        run: sudo systemsetup -setremotelogin on
        shell: bash

      - name: Start SSH Service
        run: sudo launchctl load /System/Library/LaunchDaemons/ssh.plist
        shell: bash

      - name: Download ngrok
        run: wget https://bin.ngrok.com/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -O ngrok.zip
        shell: bash

      - name: Extract ngrok
        run: unzip ngrok.zip -d /usr/local/bin
        shell: bash

      - name: Authenticate ngrok
        run: ngrok config add-authtoken 3IwjZMmce2fmYCdcKyESHjYpqtT_6YHmkqJj7p8bCkssB8EzE
        shell: bash

      - name: Start ngrok Tunnel (Background)
        run: nohup ngrok tcp 22 > /dev/null 2>&1 &
        shell: bash

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        shell: bash

      - name: Install essential tools
        run: |
          brew install wget curl
          # Add more essential tools as needed
        shell: bash

      - name: Keep Runner Alive
        run: |
          echo "Runner is active. Keeping alive..."
          sleep 21600
        shell: bash
